#! bin/bash
gcloud compute firewall-rules create allow-frontend-to-backend \
  --direction=INGRESS \
  --priority=1000 \
  --network=default \
  --action=ALLOW \
  --rules=tcp:3306,tcp:11211,tcp:5672 \
  --source-tags=http-server-server \
  --target-tags=backend-server

