#! bin/bash

gcloud dns record-sets transaction start --zone="my-private-zone"

gcloud dns record-sets transaction add 10.128.0.18 \
  --name="mc01.myapp.internal." \
  --ttl=300 \
  --type=A \
  --zone="my-private-zone"

gcloud dns record-sets transaction add 10.128.0.17 \
  --name="db01.myapp.internal." \
  --ttl=300 \
  --type=A \
  --zone="my-private-zone"

gcloud dns record-sets transaction add 10.128.0.19 \
  --name="rmq01.myapp.internal." \
  --ttl=300 \
  --type=A \
  --zone="my-private-zone"

gcloud dns record-sets transaction execute --zone="my-private-zone"

