#! bin/bash
gcloud compute instances create mysql-instance \
  --zone=us-central1-a \
  --machine-type=e2-medium \
  --image-family=debian-12 \
  --image-project=debian-cloud \
  --boot-disk-size=10GB \
  --tags=ssh,backend-server \
  --metadata-from-file=startup-script=../VMs-user-data/mysql.sh
